const fs = require("node:fs");
const path = require("node:path");
const { execFileSync: exec } = require("node:child_process");
const root = path.resolve(__dirname, "../..");
const payload = path.resolve(process.argv[2] || "build/installer-payload");
const meta = JSON.parse(fs.readFileSync(path.join(payload, "bundle.json")));
if (process.platform !== "darwin" || meta.platform !== "darwin" || !["x64", "arm64"].includes(meta.arch)) throw new Error("macOS payload required");
const directory = path.join(root, "build/installers", `macos-${meta.arch}`);
fs.rmSync(directory, { recursive: true, force: true });
const imageRoot = path.join(directory, "image");
const app = path.join(imageRoot, "WebAgentMate Connector.app");
const contents = path.join(app, "Contents");
fs.mkdirSync(path.join(contents, "MacOS"), { recursive: true });
fs.mkdirSync(path.join(contents, "Resources"), { recursive: true });
fs.cpSync(payload, path.join(contents, "Resources/bridge"), { recursive: true });
fs.copyFileSync(path.join(root, "public/icons/icon-128.png"), path.join(contents, "Resources/BridgeIcon.png"));
const info = { CFBundleIdentifier: "ai.webagentmate.bridge.installer", CFBundleName: "WebAgentMate Connector", CFBundleExecutable: "Installer", CFBundlePackageType: "APPL", CFBundleShortVersionString: meta.version, CFBundleVersion: meta.version, LSMinimumSystemVersion: "13.5", NSHighResolutionCapable: true };
const infoFile = path.join(contents, "Info.plist");
fs.writeFileSync(infoFile, JSON.stringify(info));
exec("plutil", ["-convert", "xml1", infoFile]);
exec("xcrun", ["swiftc", "-swift-version", "5", "-O", "-target", `${meta.arch === "x64" ? "x86_64" : "arm64"}-apple-macosx13.5`, "-framework", "AppKit", path.join(__dirname, "mac-app.swift"), "-o", path.join(contents, "MacOS/Installer")], { stdio: "inherit" });
const identity = process.env.WAM_MAC_SIGN_IDENTITY;
const sign = file => exec("codesign", ["--force", "--sign", identity || "-", ...(identity ? ["--timestamp", "--options", "runtime"] : []), file], { stdio: "inherit" });
exec("codesign", ["--force", "--sign", identity || "-", ...(identity ? ["--timestamp", "--options", "runtime"] : []), "--entitlements", path.join(__dirname, "node-entitlements.plist"), path.join(contents, "Resources/bridge/runtime/node/bin/node")], { stdio: "inherit" });
sign(path.join(contents, "Resources/bridge/webagentmate-bridge"));
sign(path.join(contents, "Resources/bridge/webagentmate-launcher"));
sign(app);
exec("codesign", ["--verify", "--deep", "--strict", app], { stdio: "inherit" });
fs.writeFileSync(path.join(imageRoot, "Start here.txt"), "Double-click WebAgentMate Connector, then click Install. No terminal commands or separate Node.js installation are needed.\n\n双击 WebAgentMate Connector，点击安装。无需执行命令，也无需单独安装 Node.js。\n\nRequires macOS 13.5 or newer. / 需要 macOS 13.5 或更新版本。\n");
const output = path.join(root, "release/artifacts");
fs.mkdirSync(output, { recursive: true });
const dmg = path.join(output, `webagentmate-bridge-macos-${meta.arch}.dmg`);
exec("hdiutil", ["create", "-ov", "-volname", "WebAgentMate Connector", "-srcfolder", imageRoot, "-format", "UDZO", dmg], { stdio: "inherit" });
if (identity) sign(dmg);
if (process.env.WAM_NOTARY_PROFILE) {
  if (!identity) throw new Error("Notarization requires a Developer ID signing identity");
  exec("xcrun", ["notarytool", "submit", dmg, "--keychain-profile", process.env.WAM_NOTARY_PROFILE, "--wait"], { stdio: "inherit" });
  exec("xcrun", ["stapler", "staple", dmg], { stdio: "inherit" });
  exec("xcrun", ["stapler", "validate", dmg], { stdio: "inherit" });
}
fs.writeFileSync(`${dmg}.release.json`, JSON.stringify({ signed: !!identity, notarized: !!process.env.WAM_NOTARY_PROFILE, version: meta.version }));
console.log(`${dmg}${identity && process.env.WAM_NOTARY_PROFILE ? " (notarized)" : " (development build; signing/notarization required for release)"}`);
