import type { SupportedLanguage } from "./locales";
const en = {
  title: "Automatic Connector updates", check: "Check for updates", hint: "Downloads include the runtime and are installed after local tasks finish.",
  legacy: "Install the latest Connector once to enable automatic updates.", paused: "Automatic updates are paused.", version: "Installed version",
  idle: "Ready to check", checking: "Checking for updates…", downloading: "Downloading update…", waiting_idle: "Update ready. Waiting for local tasks to finish…", applying: "Installing update…", current: "Compatible version installed", updated: "Update installed", rolled_back: "Update failed. The previous version has been restored. You can retry.", unavailable: "A compatible update has not been published yet.", error: "Could not update. Please retry."
};
type Copy = Record<keyof typeof en, string>;
const copies: Record<SupportedLanguage, Copy> = {
  en,
  zh_CN: { title: "自动更新连接助手", check: "检查更新", hint: "更新包含所需运行环境，等本地任务结束后自动安装。", legacy: "安装一次最新版连接助手，即可启用自动更新。", paused: "已暂停自动更新。", version: "已安装版本", idle: "待检查", checking: "正在检查更新…", downloading: "正在下载更新…", waiting_idle: "更新已就绪，等待本地任务结束…", applying: "正在安装更新…", current: "已安装兼容版本", updated: "更新已安装", rolled_back: "更新失败，已恢复上一版本，可以重试。", unavailable: "兼容此扩展版本的更新尚未发布。", error: "更新未完成，请重试。" },
  zh_TW: { title: "自動更新連線助手", check: "檢查更新", hint: "更新包含所需執行環境，等本機任務結束後自動安裝。", legacy: "安裝一次最新版連線助手，即可啟用自動更新。", paused: "已暫停自動更新。", version: "已安裝版本", idle: "待檢查", checking: "正在檢查更新…", downloading: "正在下載更新…", waiting_idle: "更新已就緒，等待本機任務結束…", applying: "正在安裝更新…", current: "已安裝相容版本", updated: "更新已安裝", rolled_back: "更新失敗，已還原上一版本，可以重試。", unavailable: "相容此擴充功能版本的更新尚未發布。", error: "更新未完成，請重試。" },
  ja: { title: "コネクターの自動更新", check: "更新を確認", hint: "実行環境を含む更新をダウンロードし、ローカルタスクの終了後にインストールします。", legacy: "最新のコネクターを一度インストールすると、自動更新が有効になります。", paused: "自動更新は一時停止中です。", version: "インストール済みバージョン", idle: "確認待ち", checking: "更新を確認中…", downloading: "更新をダウンロード中…", waiting_idle: "更新の準備完了。ローカルタスクの終了を待っています…", applying: "更新をインストール中…", current: "互換バージョンがインストールされています", updated: "更新をインストールしました", rolled_back: "更新に失敗し、以前のバージョンに戻しました。再試行できます。", unavailable: "互換性のある更新はまだ公開されていません。", error: "更新できませんでした。再試行してください。" },
  de: { title: "Connector automatisch aktualisieren", check: "Nach Updates suchen", hint: "Updates enthalten die Laufzeitumgebung und werden nach Abschluss lokaler Aufgaben installiert.", legacy: "Installieren Sie einmal den neuesten Connector, um automatische Updates zu aktivieren.", paused: "Automatische Updates sind pausiert.", version: "Installierte Version", idle: "Bereit zur Prüfung", checking: "Updates werden gesucht…", downloading: "Update wird heruntergeladen…", waiting_idle: "Update bereit. Lokale Aufgaben werden noch ausgeführt…", applying: "Update wird installiert…", current: "Kompatible Version installiert", updated: "Update installiert", rolled_back: "Update fehlgeschlagen. Die vorherige Version wurde wiederhergestellt. Sie können es erneut versuchen.", unavailable: "Ein kompatibles Update wurde noch nicht veröffentlicht.", error: "Update fehlgeschlagen. Bitte erneut versuchen." },
  pt_BR: { title: "Atualizações automáticas do Connector", check: "Verificar atualizações", hint: "As atualizações incluem o ambiente de execução e são instaladas após as tarefas locais terminarem.", legacy: "Instale uma vez o Connector mais recente para ativar as atualizações automáticas.", paused: "Atualizações automáticas pausadas.", version: "Versão instalada", idle: "Pronto para verificar", checking: "Verificando atualizações…", downloading: "Baixando atualização…", waiting_idle: "Atualização pronta. Aguardando o fim das tarefas locais…", applying: "Instalando atualização…", current: "Versão compatível instalada", updated: "Atualização instalada", rolled_back: "A atualização falhou. A versão anterior foi restaurada. Você pode tentar novamente.", unavailable: "Uma atualização compatível ainda não foi publicada.", error: "Não foi possível atualizar. Tente novamente." }
};
export function updateText(language: SupportedLanguage) { return copies[language]; }
