import type { SupportedLanguage as Language } from "./locales";

const en = {
  capabilities: "Codex capabilities", inherit: "Use local Codex settings", effort: "Reasoning effort", sandbox: "File and network access", approval: "Codex approvals", mode: "Working mode", serviceTier: "Service tier",
  readOnly: "Read only", workspaceWrite: "Workspace write", fullAccess: "Full access", untrusted: "Approve untrusted commands", onRequest: "When Codex requests", never: "Never request approval", defaultMode: "Execute", planMode: "Plan",
  settingsHint: "Inherits local Codex instructions, Skills, MCP and configuration. Conversation choices override only the selected options. Browser actions follow the permission control in the composer.", fullAccessHint: "Full access allows Codex commands to access files and the network outside the selected workspace.",
  skills: "Skills", mcp: "MCP servers", threads: "Codex history", refresh: "Refresh", search: "Search", more: "Load more", empty: "No results", insert: "Use skill", enabled: "Enabled", skillHint: "Enable/disable updates the local Codex configuration. Use skill inserts $name into your draft.", login: "Sign in", signedIn: "Signed in", notLoggedIn: "Not signed in", unsupported: "No OAuth", tools: "Tools", resources: "Resources",
  import: "Import as branch", importHint: "Imports a copy of Codex history. Sending the next message creates a native Codex branch; the original terminal session remains independent.",
  steer: "Add to current turn", steerHint: "Adds instructions to the running Codex turn. Enter queues a new turn; Ctrl/⌘+Enter adds to the current turn.", uncertain: "Delivery unconfirmed — check the conversation before sending again", delivering: "Sending to current turn", requested: "Waiting to send", cancel: "Cancel", submit: "Submit", decline: "Decline", openUrl: "Open authorization page", loginDone: "I have completed authorization", formUnsupported: "This server uses a form structure that is not yet supported. Decline or cancel to continue.", yes: "Yes", no: "No", usage: "Token usage", context: "Current context", reasoningSummary: "Reasoning summary", fileDiff: "File changes", plan: "Plan", contextCompaction: "Context compacted", nativeSettings: "Effective Codex settings"
};
type Key = keyof typeof en;
const zh: Record<Key, string> = {
  capabilities: "Codex 能力", inherit: "跟随本机 Codex", effort: "推理强度", sandbox: "文件与网络访问", approval: "Codex 审批策略", mode: "工作模式", serviceTier: "服务档位",
  readOnly: "只读", workspaceWrite: "工作区可写", fullAccess: "完全访问", untrusted: "不可信命令需审批", onRequest: "由 Codex 按需请求", never: "不请求审批", defaultMode: "执行", planMode: "计划",
  settingsHint: "继承本机 Codex 指令、Skills、MCP 和配置。会话选项仅覆盖你指定的设置；浏览器操作仍遵循输入框中的权限开关。", fullAccessHint: "完全访问允许 Codex 命令读写工作目录以外的文件并访问网络。",
  skills: "Skills", mcp: "MCP 服务", threads: "Codex 历史", refresh: "刷新", search: "搜索", more: "加载更多", empty: "暂无结果", insert: "使用技能", enabled: "启用", skillHint: "启用开关会更新本机 Codex 配置；使用技能会将 $名称 插入草稿。", login: "登录", signedIn: "已登录", notLoggedIn: "未登录", unsupported: "无需 OAuth", tools: "工具", resources: "资源",
  import: "导入为分支", importHint: "复制 Codex 历史。发送下一条消息时创建原生 Codex 分支，原终端会话保持独立。",
  steer: "追加到当前轮", steerHint: "向运行中的 Codex 追加指令。Enter 排队下一轮，Ctrl/⌘+Enter 追加到当前轮。", uncertain: "发送结果未确认，请查看会话后再决定是否重发", delivering: "正在追加到当前轮", requested: "等待追加", cancel: "取消", submit: "提交", decline: "拒绝", openUrl: "打开授权页面", loginDone: "我已完成授权", formUnsupported: "暂不支持此服务的高级表单结构，可拒绝或取消后继续。", yes: "是", no: "否", usage: "Token 用量", context: "当前上下文", reasoningSummary: "推理摘要", fileDiff: "文件变更", plan: "计划", contextCompaction: "上下文已压缩", nativeSettings: "Codex 生效配置"
};
const translations: Partial<Record<Language, Partial<Record<Key, string>>>> = {
  zh_CN: zh,
  zh_TW: { ...zh, capabilities: "Codex 能力", inherit: "跟隨本機 Codex", effort: "推理強度", sandbox: "檔案與網路存取", approval: "Codex 核准策略", mode: "工作模式", serviceTier: "服務等級", readOnly: "唯讀", workspaceWrite: "工作區可寫", fullAccess: "完整存取", threads: "Codex 歷史", refresh: "重新整理", search: "搜尋", more: "載入更多", empty: "沒有結果", insert: "使用技能", enabled: "啟用", login: "登入", import: "匯入為分支", steer: "加入目前回合", cancel: "取消", submit: "提交", decline: "拒絕", openUrl: "開啟授權頁面", loginDone: "我已完成授權", usage: "Token 用量", context: "目前上下文", fileDiff: "檔案變更", plan: "計畫" },
  ja: { capabilities: "Codex の機能", inherit: "ローカル Codex の設定を使用", effort: "推論の強度", sandbox: "ファイルとネットワークのアクセス", approval: "Codex の承認", mode: "作業モード", serviceTier: "サービス階層", readOnly: "読み取り専用", workspaceWrite: "作業領域に書き込み", fullAccess: "フルアクセス", untrusted: "信頼されていないコマンドを承認", onRequest: "Codex が要求したとき", never: "承認を要求しない", defaultMode: "実行", planMode: "計画", threads: "Codex の履歴", refresh: "更新", search: "検索", more: "さらに読み込む", empty: "結果なし", insert: "スキルを使用", enabled: "有効", login: "ログイン", import: "分岐としてインポート", steer: "現在のターンに追加", cancel: "キャンセル", submit: "送信", decline: "拒否", openUrl: "認証ページを開く", loginDone: "認証を完了しました", yes: "はい", no: "いいえ", usage: "トークン使用量", context: "現在のコンテキスト", reasoningSummary: "推論の要約", fileDiff: "ファイルの変更", plan: "計画", contextCompaction: "コンテキストを圧縮しました" },
  de: { capabilities: "Codex-Funktionen", inherit: "Lokale Codex-Einstellungen", effort: "Denkaufwand", sandbox: "Datei- und Netzwerkzugriff", approval: "Codex-Genehmigungen", mode: "Arbeitsmodus", serviceTier: "Servicestufe", readOnly: "Nur lesen", workspaceWrite: "Arbeitsbereich beschreiben", fullAccess: "Vollzugriff", untrusted: "Nicht vertrauenswürdige Befehle genehmigen", onRequest: "Auf Anfrage von Codex", never: "Keine Genehmigung anfordern", defaultMode: "Ausführen", planMode: "Planen", threads: "Codex-Verlauf", refresh: "Aktualisieren", search: "Suchen", more: "Mehr laden", empty: "Keine Ergebnisse", insert: "Skill verwenden", enabled: "Aktiviert", login: "Anmelden", import: "Als Abzweigung importieren", steer: "Zur aktuellen Runde hinzufügen", cancel: "Abbrechen", submit: "Senden", decline: "Ablehnen", openUrl: "Autorisierungsseite öffnen", loginDone: "Autorisierung abgeschlossen", yes: "Ja", no: "Nein", usage: "Tokenverbrauch", context: "Aktueller Kontext", reasoningSummary: "Zusammenfassung der Überlegungen", fileDiff: "Dateiänderungen", plan: "Plan", contextCompaction: "Kontext komprimiert" },
  pt_BR: { capabilities: "Recursos do Codex", inherit: "Usar configurações locais do Codex", effort: "Esforço de raciocínio", sandbox: "Acesso a arquivos e rede", approval: "Aprovações do Codex", mode: "Modo de trabalho", serviceTier: "Nível de serviço", readOnly: "Somente leitura", workspaceWrite: "Gravar no espaço de trabalho", fullAccess: "Acesso total", untrusted: "Aprovar comandos não confiáveis", onRequest: "Quando o Codex solicitar", never: "Nunca solicitar aprovação", defaultMode: "Executar", planMode: "Planejar", threads: "Histórico do Codex", refresh: "Atualizar", search: "Buscar", more: "Carregar mais", empty: "Nenhum resultado", insert: "Usar habilidade", enabled: "Ativado", login: "Entrar", import: "Importar como ramificação", steer: "Adicionar ao turno atual", cancel: "Cancelar", submit: "Enviar", decline: "Recusar", openUrl: "Abrir página de autorização", loginDone: "Concluí a autorização", yes: "Sim", no: "Não", usage: "Uso de tokens", context: "Contexto atual", reasoningSummary: "Resumo do raciocínio", fileDiff: "Alterações em arquivos", plan: "Plano", contextCompaction: "Contexto compactado" }
};
export function codexText(language: Language, key: Key): string { return translations[language]?.[key] ?? en[key]; }
