import type { SupportedLanguage } from "./locales";
import { interactionText, type InteractionKey } from "./workspace-interaction-i18n";
const en = {
  openInPage: "Open in a separate page", limitToolCalls: "Limit tool calls", limited: "Limited", unlimited: "Unlimited", toolLimitHint: "Off by default. Runs continue until completion or a manual stop. Repeated failures or unchanged tool loops pause the run; individual requests still have timeouts.",
  sessionSynced: "This conversation is running. Progress is synced; you can stop it or respond here.", checkingRun: "Checking the previous run. You can stop or recover it here.", stopping: "Stopping…", draftConflict: "The draft changed in another window. Your unsaved text is still here; copy it before switching conversations.",
  directoryUnavailable: "Cannot connect to the local Bridge. Check its installation, reload the extension, then retry.", directoryTimeout: "Reading the folder timed out. Try again or choose another path.", directoryInvalid: "Enter an existing folder using its absolute path.", directoryDenied: "Permission to read this folder was denied. Choose an accessible folder.", directoryFailed: "Could not read the folder. Check the path and retry.", directoryUpdate: "Update the local Bridge to use the folder picker.", retry: "Retry",
  chooseDirectory: "Choose a folder", useDirectory: "Use this folder", browse: "Browse folders", recentDirectories: "Recent folders", directoryPath: "Enter an absolute folder path", parentDirectory: "Parent folder", noDirectories: "No subfolders", more: "Load more", modelSearch: "Search provider or model", apiKey: "API key", browserLogin: "Browser sign-in", keyConnect: "Verify and connect", keyHint: "Create a key in your OrcaRouter account. It stays in this browser.", connectionHint: "Needed only for the built-in agent. Codex and Claude Code use their own sign-in.", localConnectionHint: "All agents run through this Bridge and connect to browser tools.", connectedReady: "Connected and ready", authWindowFailed: "Sign-in did not finish. Retry, or connect with an API key.", authKeyInvalid: "Enter a valid OrcaRouter API key starting with sk-orca-.", authRejected: "The key was rejected. Check that it is valid and has not been revoked.", authTimeout: "The connection timed out. Check your network and try again.", authFailed: "Connection failed. Retry or use an API key.", authDeclined: "Authorization was cancelled. Your existing connection was kept.", connectionSaved: "OrcaRouter connected successfully.", provider: "Provider", defaultFolder: "Use default folder", apiKeysLink: "Get an API key", actions: "Conversation actions",
  import: "Import backup", fork: "Branch conversation", branch: "Branched from", allSessions: "All locations", interrupted: "Interrupted", invalidBackup: "This file is not a supported conversation backup.", backupTooLarge: "Conversation backups can be up to 10 MB.",
  sessions: "Conversations", search: "Search conversations", rename: "Rename", remove: "Delete", export: "Export", save: "Save", cancel: "Cancel", builtin: "Built-in agent", engine: "Agent engine", workspace: "Working directory", defaultWorkspace: "Default private workspace", defaultModel: "Agent default", steps: "Tool-call limit", continue: "Continue", recover: "Recover interrupted conversation", workingElsewhere: "Another conversation is running", empty: "No conversations found", running: "Working", approval: "Permission required", question: "Your input is needed", allow: "Allow once", deny: "Deny", reply: "Reply", deleteConfirm: "Delete this conversation and its local history? Native agent transcripts and created files are not deleted.", restartNotice: "The previous run was interrupted. Completed actions were not rolled back. Inspect the current state before continuing.", bridgeRequired: "Install or update the local Bridge with Node 20+, then refresh the connection. Your conversations and drafts are preserved.", connectRequired: "Connect OrcaRouter in Settings first.", branchNotice: "Changing the engine or working directory creates a conversation branch with the visible chat history. The original conversation is preserved.", localNotice: "Local tools run on this computer. Models may still be hosted remotely. File and page content can be sent to the selected provider.", browserNotice: "Browser tools only. Closing this panel stops the current run; your conversation is saved.", sessionBusy: "This conversation is running. You can stop it in the current window.", stopped: "Stopped. Already completed actions have not been undone.", limits: "This model hit a quota or request limit. Change the model below; no paid model will be selected automatically.", title: "Conversation title", loadingModels: "Loading models…", modelFailure: "Could not load models. You can use the agent default or enter a model ID.", tools: "Tool details", inputHint: "Enter to send · Shift+Enter for a new line", noCredential: "Backups include chats, drafts and tool records, without the app connection settings.", privacy: "History and tool results are stored only on this device. Selected content is sent to your model provider. Delete conversations to remove the extension's copy.", node: "Local Bridge", nativeHint: "Codex/Claude retain their own session history. SDK authentication and provider usage limits apply.", artifact: "Download document"
};
type Key = keyof typeof en;
const zh: Record<Key, string> = {
  openInPage: "在独立页面打开", limitToolCalls: "限制工具调用次数", limited: "已限制", unlimited: "不限", toolLimitHint: "默认不限次数和整轮时长，可随时手动停止。连续失败或工具循环无进展时会暂停，单次请求仍有超时保护。",
  sessionSynced: "会话正在运行，进度已同步。可以在当前窗口停止任务或回复。", checkingRun: "正在检查上次运行状态，可以在当前窗口停止或恢复。", stopping: "正在停止…", draftConflict: "草稿已在其他窗口修改。当前未保存的文字仍保留，请先复制再切换会话。",
  directoryUnavailable: "无法连接本机 Bridge，请检查安装并重新加载扩展后重试。", directoryTimeout: "读取目录超时，请重试或选择其他路径。", directoryInvalid: "请输入已存在文件夹的绝对路径。", directoryDenied: "没有读取此目录的权限，请选择可访问的文件夹。", directoryFailed: "读取目录失败，请检查路径后重试。", directoryUpdate: "请更新本机 Bridge 后再使用目录选择器。", retry: "重试",
  chooseDirectory: "选择工作目录", useDirectory: "使用此目录", browse: "浏览文件夹", recentDirectories: "最近使用", directoryPath: "输入文件夹绝对路径", parentDirectory: "上一级", noDirectories: "没有子文件夹", more: "加载更多", modelSearch: "搜索服务商或模型", apiKey: "API Key", browserLogin: "浏览器登录", keyConnect: "验证并连接", keyHint: "在 OrcaRouter 账户中创建密钥，仅保存在当前浏览器。", connectionHint: "仅内置智能体需要；Codex / Claude Code 使用各自的登录。", localConnectionHint: "所有智能体通过本机 Bridge 运行，并连接浏览器工具。", connectedReady: "已连接，可以使用", authWindowFailed: "登录未完成，请重试，或使用 API Key 连接。", authKeyInvalid: "请输入以 sk-orca- 开头的有效 OrcaRouter API Key。", authRejected: "密钥被拒绝，请检查是否有效或已被撤销。", authTimeout: "连接超时，请检查网络后重试。", authFailed: "连接失败，请重试或使用 API Key。", authDeclined: "已取消授权，原有连接保持不变。", connectionSaved: "OrcaRouter 连接成功。", provider: "服务商", defaultFolder: "使用默认目录", apiKeysLink: "获取 API Key", actions: "会话操作",
  import: "导入备份", fork: "创建会话分支", branch: "分支来源", allSessions: "全部环境", interrupted: "已中断", invalidBackup: "这个文件不是受支持的会话备份。", backupTooLarge: "会话备份大小最多为 10 MB。",
  sessions: "会话", search: "搜索会话", rename: "重命名", remove: "删除", export: "导出", save: "保存", cancel: "取消", builtin: "内置智能体", engine: "智能体引擎", workspace: "工作目录", defaultWorkspace: "默认私有工作目录", defaultModel: "智能体默认模型", steps: "工具调用上限", continue: "继续", recover: "恢复中断的会话", workingElsewhere: "另一个会话正在运行", empty: "没有找到会话", running: "处理中", approval: "需要操作授权", question: "需要你补充信息", allow: "仅允许本次", deny: "拒绝", reply: "回复", deleteConfirm: "删除这个会话及其本地记录？不会删除本地智能体自身的历史或已创建的文件。", restartNotice: "上次运行已中断，已完成的操作没有回滚。继续前需要检查当前状态。", bridgeRequired: "请先安装或更新本机 Bridge（需 Node 20+），再刷新连接状态。会话记录和草稿会保留。", connectRequired: "请先在设置中连接 OrcaRouter。", branchNotice: "更改引擎或工作目录时，将保留原会话，并携带可见聊天记录创建分支。", localNotice: "智能体在本机运行，模型仍可能由云端服务提供。所选文件及网页内容可能发送给模型服务商。", browserNotice: "仅使用浏览器工具。关闭侧栏会停止当前任务，会话记录会保存。", sessionBusy: "这个会话正在运行，可以在当前窗口停止后继续。", stopped: "已停止。已经完成的操作不会自动撤销。", limits: "当前模型触发了额度或请求限制，请选择其他模型。不会自动切换到付费模型。", title: "会话名称", loadingModels: "正在获取模型…", modelFailure: "模型列表获取失败，可以使用智能体默认模型或输入模型 ID。", tools: "工具详情", inputHint: "Enter 发送 · Shift+Enter 换行", noCredential: "备份包含聊天、草稿和工具记录，不包含应用连接设置。", privacy: "会话和工具结果仅保存在当前设备；所选内容会发送给模型服务商。删除会话可移除扩展保存的副本。", node: "本机 Bridge", nativeHint: "Codex / Claude 会保留各自的会话历史，仍受其鉴权方式和服务额度限制。", artifact: "下载文档"
};
const extra: Partial<Record<SupportedLanguage, Partial<Record<Key, string>>>> = {
  zh_TW: { node: "本機 Bridge", connectionHint: "僅內建智慧體需要；Codex / Claude Code 使用各自的登入。", localConnectionHint: "所有智慧體透過本機 Bridge 執行，並連接瀏覽器工具。", bridgeRequired: "請先安裝或更新本機 Bridge（需 Node 20+），再重新整理連線狀態。會話與草稿會保留。", branchNotice: "更改引擎或工作目錄時，會保留原會話並攜帶可見聊天記錄建立分支。", localNotice: "智慧體在本機執行，模型仍可能由雲端服務提供。所選檔案及網頁內容可能傳送給模型服務商。", openInPage: "在獨立頁面開啟", limitToolCalls: "限制工具呼叫次數", limited: "已限制", unlimited: "不限", toolLimitHint: "預設不限次數與整輪時間，可隨時手動停止。連續失敗或工具循環無進展時會暫停，單次請求仍有逾時保護。", sessions: "會話", search: "搜尋會話", rename: "重新命名", remove: "刪除", export: "匯出", save: "儲存", cancel: "取消", builtin: "內建智慧體", engine: "智慧體引擎", workspace: "工作目錄", continue: "繼續", allow: "僅允許本次", deny: "拒絕", reply: "回覆" },
  ja: { node: "ローカル Bridge", connectionHint: "内蔵エージェントのみ必要です。Codex と Claude Code は独自の認証を使います。", localConnectionHint: "すべてのエージェントは Bridge 経由で動作し、ブラウザーツールに接続します。", bridgeRequired: "Node 20+ とローカル Bridge をインストールまたは更新し、接続状態を更新してください。会話と下書きは保存されます。", branchNotice: "エンジンや作業ディレクトリを変更すると、元の会話を保持したまま会話が分岐します。", openInPage: "独立したページで開く", limitToolCalls: "ツール呼び出しを制限", limited: "制限あり", unlimited: "無制限", toolLimitHint: "初期設定では回数とタスク全体の時間に上限はありません。手動停止できます。失敗や変化のない処理が続くと一時停止します。個別のリクエストにはタイムアウトがあります。", sessions: "会話", search: "会話を検索", rename: "名前を変更", remove: "削除", export: "エクスポート", save: "保存", cancel: "キャンセル", builtin: "内蔵エージェント", engine: "エージェント", workspace: "作業ディレクトリ", continue: "続行", allow: "今回のみ許可", deny: "拒否", reply: "返信" },
  de: { node: "Lokale Bridge", connectionHint: "Nur für den integrierten Agenten nötig. Codex und Claude Code verwenden ihre eigene Anmeldung.", localConnectionHint: "Alle Agenten laufen über diese Bridge und nutzen die Browser-Tools.", bridgeRequired: "Installieren oder aktualisieren Sie die lokale Bridge mit Node 20+ und aktualisieren Sie den Verbindungsstatus. Unterhaltungen und Entwürfe bleiben erhalten.", branchNotice: "Ein Wechsel von Agent oder Arbeitsverzeichnis erstellt einen Zweig mit dem sichtbaren Chatverlauf. Das Original bleibt erhalten.", openInPage: "Auf eigener Seite öffnen", limitToolCalls: "Tool-Aufrufe begrenzen", limited: "Begrenzt", unlimited: "Unbegrenzt", toolLimitHint: "Standardmäßig ohne Aufruf- oder Gesamtlaufzeitlimit. Manuelles Stoppen bleibt möglich. Wiederholte Fehler oder unveränderte Abläufe pausieren die Aufgabe; einzelne Anfragen haben Zeitlimits.", sessions: "Unterhaltungen", search: "Unterhaltungen suchen", rename: "Umbenennen", remove: "Löschen", export: "Exportieren", save: "Speichern", cancel: "Abbrechen", builtin: "Integrierter Agent", engine: "Agent", workspace: "Arbeitsverzeichnis", continue: "Fortsetzen", allow: "Einmal erlauben", deny: "Ablehnen", reply: "Antworten" },
  pt_BR: { node: "Bridge local", connectionHint: "Necessário apenas para o agente integrado. Codex e Claude Code usam suas próprias autenticações.", localConnectionHint: "Todos os agentes executam por este Bridge e usam ferramentas do navegador.", bridgeRequired: "Instale ou atualize o Bridge local com Node 20+ e atualize o status da conexão. Conversas e rascunhos serão preservados.", branchNotice: "Alterar o agente ou diretório de trabalho cria uma ramificação com o histórico visível. A conversa original é preservada.", openInPage: "Abrir em página separada", limitToolCalls: "Limitar chamadas de ferramentas", limited: "Limitado", unlimited: "Ilimitado", toolLimitHint: "Sem limite de chamadas ou duração total por padrão. Você pode parar manualmente. Falhas ou ciclos sem mudanças pausam a tarefa; cada solicitação mantém seu tempo limite.", sessions: "Conversas", search: "Buscar conversas", rename: "Renomear", remove: "Excluir", export: "Exportar", save: "Salvar", cancel: "Cancelar", builtin: "Agente integrado", engine: "Agente", workspace: "Diretório de trabalho", continue: "Continuar", allow: "Permitir uma vez", deny: "Negar", reply: "Responder" }
};
const sessionExtras: Partial<Record<SupportedLanguage, Partial<Record<Key, string>>>> = {
  zh_TW: { import: "匯入備份", fork: "建立會話分支", branch: "分支來源", allSessions: "全部環境", interrupted: "已中斷", invalidBackup: "這個檔案不是支援的會話備份。", backupTooLarge: "會話備份大小最多為 10 MB。", empty: "找不到會話", noCredential: "備份包含聊天、草稿與工具記錄，不包含應用程式的連線設定。" },
  ja: { import: "バックアップを読み込む", fork: "会話を分岐", branch: "分岐元", allSessions: "すべての環境", interrupted: "中断", invalidBackup: "対応している会話バックアップではありません。", backupTooLarge: "会話バックアップは 10 MB までです。", empty: "会話が見つかりません", noCredential: "バックアップには会話、下書き、ツールの記録が含まれます。接続設定は含まれません。" },
  de: { import: "Backup importieren", fork: "Unterhaltung verzweigen", branch: "Abgezweigt von", allSessions: "Alle Umgebungen", interrupted: "Unterbrochen", invalidBackup: "Diese Datei ist kein unterstütztes Unterhaltungsbackup.", backupTooLarge: "Unterhaltungsbackups dürfen höchstens 10 MB groß sein.", empty: "Keine Unterhaltungen gefunden", noCredential: "Backups enthalten Chats, Entwürfe und Tool-Protokolle, aber keine Verbindungseinstellungen." },
  pt_BR: { import: "Importar backup", fork: "Criar ramificação", branch: "Ramificação de", allSessions: "Todos os ambientes", interrupted: "Interrompida", invalidBackup: "Este arquivo não é um backup de conversa compatível.", backupTooLarge: "Backups de conversas podem ter até 10 MB.", empty: "Nenhuma conversa encontrada", noCredential: "O backup inclui conversas, rascunhos e registros de ferramentas, sem as configurações de conexão." }
};
export function workspaceText(language: SupportedLanguage, key: Key | InteractionKey): string {
  const interaction = interactionText(language, key);
  if (interaction !== undefined) return interaction;
  const base = key as Key;
  return sessionExtras[language]?.[base] ?? extra[language]?.[base] ?? (language.startsWith("zh") ? zh[base] : en[base]);
}

type Phase = import("./agent/protocol").RunPhase;
const phases: Record<SupportedLanguage, Record<Phase, string>> = {
  en: { connecting: "Connecting to the model", thinking: "Thinking", executing: "Running a tool", waiting: "Waiting for your input", compacting: "Summarizing earlier context", retrying: "Retrying the connection" },
  zh_CN: { connecting: "正在连接模型", thinking: "正在思考", executing: "正在执行工具", waiting: "等待你的回复", compacting: "正在整理较早的上下文", retrying: "正在重试连接" },
  zh_TW: { connecting: "正在連線模型", thinking: "正在思考", executing: "正在執行工具", waiting: "等待你的回覆", compacting: "正在整理較早的上下文", retrying: "正在重試連線" },
  ja: { connecting: "モデルに接続中", thinking: "考え中", executing: "ツールを実行中", waiting: "入力を待っています", compacting: "以前の会話を要約中", retrying: "接続を再試行中" },
  de: { connecting: "Verbindung zum Modell wird hergestellt", thinking: "Wird durchdacht", executing: "Tool wird ausgeführt", waiting: "Wartet auf Ihre Eingabe", compacting: "Früherer Kontext wird zusammengefasst", retrying: "Verbindung wird erneut versucht" },
  pt_BR: { connecting: "Conectando ao modelo", thinking: "Pensando", executing: "Executando ferramenta", waiting: "Aguardando sua resposta", compacting: "Resumindo o contexto anterior", retrying: "Tentando conectar novamente" }
};
export function phaseText(language: SupportedLanguage, phase: Phase): string { return phases[language][phase]; }
export function turnLimitText(language: SupportedLanguage): string {
  return { en: "Model turn limit", zh_CN: "模型轮次上限", zh_TW: "模型輪次上限", ja: "モデルの最大ターン数", de: "Maximale Modellrunden", pt_BR: "Limite de turnos do modelo" }[language];
}
